In [84]:
from bs4 import BeautifulSoup
import requests
import smtplib
import time
import datetime
import os 
import csv
import openpyxl
import pandas as pd

In [91]:
url = 'https://www.imdb.com/chart/top/'
#headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36","Accept-Encoding": "gzip, deflate","Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8","Dnt": "1","Connection":"close","Upgrade-Insecure-Requests": "1"}


#open/create csv file
# header = ['Rank','Name','Year','Rating']
# with open('imdbmovie250.csv','w',newline= "",encoding="UTF-8") as f:
#     writer = csv.writer(f)
#     writer.writerow(header)


#excel file loading
excel = openpyxl.Workbook()
#print(excel.sheetnames)
sheet = excel.active
sheet.title = "movieRatings"
print(excel.sheetnames)
sheet.append(['Rank','Name','Year','Rating'])
try:
    page = requests.get(url)
    page.raise_for_status()

    soup1 = BeautifulSoup(page.text,"html.parser")
    soup2 = BeautifulSoup(soup1.prettify(),"html.parser")
    
    movies = soup2.find('tbody',class_ ="lister-list").find_all('tr')
    #print(len(movie_title))
    
    for moviename in movies:
        #movie = moviename.find('td',class_='titleColumn').get_text()#-- to get every text in that tag td
        name = moviename.find('td',class_='titleColumn').a.text.strip()
        rank = moviename.find('td',class_='titleColumn').get_text(strip=True).split('.')[0]
        year = moviename.find('td',class_='titleColumn').span.text.split('(')[1].split(')')[0]  #strip not working 
        rating = moviename.find('td',class_='ratingColumn imdbRating').strong.text.strip()
        data = [rank,name,year,rating]
        #print(data)
        #append data csv file
#         with open('imdbmovie250.csv','a+',newline= "",encoding="UTF-8") as f:
#             writer = csv.writer(f)
#             writer.writerow(data)


        #appending in xlsx
        sheet.append(data)
        
except Exception as e:
    print(e)

#print(soup2)  
#print(movie_title)
excel.save('IMDBmovieRatings.xlsx')

['movieRatings']

In [82]:
df = pd.read_csv('imdbmovie250.csv')
df

     Rank                      Name  Year  Rating
0       1  The Shawshank Redemption  1994     9.2
1       2             The Godfather  1972     9.2
2       3           The Dark Knight  2008     9.0
3       4     The Godfather Part II  1974     9.0
4       5              12 Angry Men  1957     9.0
..    ...                       ...   ...     ...
245   246            The Iron Giant  1999     8.0
246   247                  The Help  2011     8.0
247   248                   Aladdin  1992     8.0
248   249               Dersu Uzala  1975     8.0
249   250        Dances with Wolves  1990     8.0

[250 rows x 4 columns]

In [92]:
df=pd.read_excel('IMDBmovieRatings.xlsx')
df

     Rank                      Name  Year  Rating
0       1  The Shawshank Redemption  1994     9.2
1       2             The Godfather  1972     9.2
2       3           The Dark Knight  2008     9.0
3       4     The Godfather Part II  1974     9.0
4       5              12 Angry Men  1957     9.0
..    ...                       ...   ...     ...
245   246            The Iron Giant  1999     8.0
246   247                  The Help  2011     8.0
247   248                   Aladdin  1992     8.0
248   249               Dersu Uzala  1975     8.0
249   250        Dances with Wolves  1990     8.0

[250 rows x 4 columns]